### ISSUE TITLE
[BUG] Python 3.9 no funciona

### ISSUE THREAD

**Issue by jbagot** [ctrl-alt-d/django-aula#171]
>Atenció! No incloure dades sensibles en aquest formulari.

**Descripció el problema**

He posat python 3.9 i no funciona 

**Passes per reproduir-ho**
Executar el projecte amb  python3.9
 
**Comportament esperat*

Que funcioni amb normalitat sense problemes.

**Traces**

```
web_1  | Traceback (most recent call last):
web_1  |   File "/app/manage.py", line 15, in <module>
web_1  |     execute_from_command_line(sys.argv)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
web_1  |     utility.execute()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
web_1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
web_1  |     self.execute(*args, **cmd_options)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 393, in execute
web_1  |     self.check()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 419, in check
web_1  |     all_issues = checks.run_checks(
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/checks/registry.py", line 76, in run_checks
web_1  |     new_errors = check(app_configs=app_configs, databases=databases)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/checks/urls.py", line 13, in check_url_config
web_1  |     return check_resolver(resolver)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/checks/urls.py", line 23, in check_resolver
web_1  |     return check_method()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 412, in check
web_1  |     for pattern in self.url_patterns:
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
web_1  |     res = instance.__dict__[self.name] = self.func(instance)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 598, in url_patterns
web_1  |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
web_1  |     res = instance.__dict__[self.name] = self.func(instance)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
web_1  |     return import_module(self.urlconf_name)
web_1  |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
web_1  |     return _bootstrap._gcd_import(name[level:], package, level)
web_1  |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
web_1  |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
web_1  |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
web_1  |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
web_1  |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
web_1  |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
web_1  |   File "/app/aula/urls.py", line 43, in <module>
web_1  |     url(r'^baixes/', include('aula.apps.baixes.urls')),
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/urls/conf.py", line 34, in include
web_1  |     urlconf_module = import_module(urlconf_module)
web_1  |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
web_1  |     return _bootstrap._gcd_import(name[level:], package, level)
web_1  |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
web_1  |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
web_1  |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
web_1  |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
web_1  |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
web_1  |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
web_1  |   File "/app/aula/apps/baixes/urls.py", line 2, in <module>
web_1  |     from   aula.apps.baixes import views as baixes_views
web_1  |   File "/app/aula/apps/baixes/views.py", line 19, in <module>
web_1  |     from aula.apps.baixes.rpt_carpeta import reportBaixaCarpeta
web_1  |   File "/app/aula/apps/baixes/rpt_carpeta.py", line 11, in <module>
web_1  |     from appy.pod.renderer import Renderer
web_1  |   File "/usr/local/lib/python3.9/site-packages/appy/pod/renderer.py", line 15, in <module>
web_1  |     from appy.pod.xhtml2odt import Xhtml2OdtConverter
web_1  |   File "/usr/local/lib/python3.9/site-packages/appy/pod/xhtml2odt.py", line 8, in <module>
web_1  |     from appy.pod.styles_manager import \
web_1  |   File "/usr/local/lib/python3.9/site-packages/appy/pod/styles_manager.py", line 9, in <module>
web_1  |     from appy.pod.doc_importers import px2cm as px2cmRatio
web_1  |   File "/usr/local/lib/python3.9/site-packages/appy/pod/doc_importers.py", line 11, in <module>
web_1  |     from appy.http.client import Resource
web_1  |   File "/usr/local/lib/python3.9/site-packages/appy/http/client.py", line 6, in <module>
web_1  |     from base64 import encodestring
web_1  | ImportError: cannot import name 'encodestring' from 'base64' (/usr/local/lib/python3.9/base64.py)
```

**Comment by amorilla** [comment]
Hola,
És un problema amb appy.pod, s'ha de modificar requirements.txt per carregar la versió correcte.
git+https://github.com/lino-framework/appypod.git#egg=appy ; python_version < '3.9'
appy ; python_version > '3.8'

Després:
source venv/bin/activate
pip uninstall appy
pip install -r requirements.txt

De totes maneres s'haurien de fer proves completes per verificar que tot és ok.
Per exemple a sincronitzaSaga.py s'ha de treure "from appy.pod.buffers import ELSE_WITHOUT_IF"

Salutacions.
